/*
 * DO NOT EDIT THIS FILE, ELSE YOU WILL NOT BE UP TO DATE WITH CHANGES OCCURRED TO THE DEFAULT TEMPLATE STRUCTURE
 *
 * Deviant Coder's ByondBoost Setup Template ver 2.000
 * This is a useful starting point for a BYONDBoost Project
 *
 * Template Structure Changelog
 * ----------------------------
 *
 * Changelog June 29, 2018 - Deviant Coder
 * 		Uses BYOND Boost Ver 2.0, and Better Documentation. No Longer Supports BYOND 511.
 */